updates and tidying stuff up

diff --git a/kubernetes/overlays/stage/etc/sdf_cluster.yml b/kubernetes/overlays/stage/etc/sdf_cluster.yml
--- a/kubernetes/overlays/stage/etc/sdf_cluster.yml
+++ b/kubernetes/overlays/stage/etc/sdf_cluster.yml
@@ -22,85 +22,64 @@ v2:
       set_host: "host=$(hostname -s)"
     vnc:
       script_wrapper: |
-        export WEBSOCKIFY_CMD="websockify"
+        # take the user defined context file and parse anything in upper case as environment variables
+        eval export $(cat user_defined_context.json | awk '$1 ~ /^.*\"[[:upper:]]+/{ split($0,a,": "); gsub(/\"/,"",a[1]); gsub(/ /,"",a[1]); gsub(/,\s*$/, "", a[2]); print a[1] "=" a[2] }')
+
+        # pre-script
+        echo -e $(cat user_defined_context.json | awk '/OOD_BOOTSTRAP_SCRIPT/{ gsub(/^\s+\"OOD_BOOTSTRAP_SCRIPT\": \"/,"",$0); gsub(/\"\,\s*$/,"",$0); gsub(/\\r/,"",$0); print $0 }') > bootstrap_script.sh
+        source bootstrap_script.sh 
+
         export XDG_RUNTIME_DIR=$(mktemp -d)
-
-        # start the container instance
-        export SINGULARITY_IMAGE=${SINGULARITY_IMAGE:-/sdf/sw/images/xfce/ubuntu18.04/xfce@ubuntu18.04.sif}
-        export SINGULARITY_INSTANCE=$(basename -- $XDG_RUNTIME_DIR) 
-
-        # start container
-        echo "Starting image ${SINGULARITY_IMAGE} as ${SINGULARITY_INSTANCE}..."
-        singularity instance start -B /sdf,/gpfs,/scratch,/lscratch --nv ${SINGULARITY_IMAGE} ${SINGULARITY_INSTANCE}
-
-        # alias doesn't work for some reason...
-        function kill(){ singularity exec instance://${SINGULARITY_INSTANCE} kill $@; }
-        export -f kill
-        function pkill(){ singularity exec instance://${SINGULARITY_INSTANCE} pkill $@; }
-        export -f pkill
-        function pgrep(){ singularity exec instance://${SINGULARITY_INSTANCE} pgrep $@; }
-        export -f pgrep
-        function vncserver(){ singularity exec instance://${SINGULARITY_INSTANCE} vncserver $@; }
-        export -f vncserver
-        function vncpasswd(){ singularity exec instance://${SINGULARITY_INSTANCE} vncpasswd $@; }
-        export -f vncpasswd
-
-        function xfconf-query(){ singularity exec instance://${SINGULARITY_INSTANCE} xfconf-query $@; }
-        export -f xfconf-query
-        function xfce4-session(){ singularity exec instance://${SINGULARITY_INSTANCE} xfce4-session $@; }
-        export -f xfce4-session
-
-        function gsettings(){ singularity exec instance://${SINGULARITY_INSTANCE} gsettings $@; }
-        export -f gsettings
-        function dconf(){ singularity exec instance://${SINGULARITY_INSTANCE} dconf $@; }
-        export -f dconf
-        function mate-session(){ singularity exec instance://${SINGULARITY_INSTANCE} mate-session $@; }
-        export -f mate-session
-
-        function websockify(){ singularity exec instance://${SINGULARITY_INSTANCE} websockify $@; }
-        export -f websockify
-
-        %s
-      set_host: "host=$(hostname -s)"
-    desktop:
-      script_wrapper: |
-
-        echo "DESKTOP VNC"
-
         export WEBSOCKIFY_CMD="websockify"
-        export XDG_RUNTIME_DIR=$(mktemp -d)
 
-        # start the container instance
-        export SINGULARITY_IMAGE=/afs/slac/package/singularity/images/xfce/ubuntu18.04/xfce@ubuntu18.04.sif
-        export SINGULARITY_INSTANCE=$(basename -- $XDG_RUNTIME_DIR)
-        singularity instance start -B /gpfs,/nfs,/afs,/scratch --nv ${SINGULARITY_IMAGE} ${SINGULARITY_INSTANCE}
+        # deal with booting up a singularity image
+        if [ ! -z "$SINGULARITY_IMAGE" ]; then
 
-        # alias doesn't work for some reason...
-        function kill(){ singularity exec instance://${SINGULARITY_INSTANCE} kill $@; }
-        export -f kill
-        function pkill(){ singularity exec instance://${SINGULARITY_INSTANCE} pkill $@; }
-        export -f pkill
-        function pgrep(){ singularity exec instance://${SINGULARITY_INSTANCE} pgrep $@; }
-        export -f pgrep
-        function vncserver(){ singularity exec instance://${SINGULARITY_INSTANCE} vncserver $@; }
-        export -f vncserver
-        function vncpasswd(){ singularity exec instance://${SINGULARITY_INSTANCE} vncpasswd $@; }
-        export -f vncpasswd
+          printenv SINGULARITY_IMAGE_TAG
+          echo $(echo $SINGULARITY_IMAGE | sed "s:#SINGULARITY_IMAGE_TAG:${SINGULARITY_IMAGE_TAG}:g")
+          # parse any variables help in image name
+          eval export SINGULARITY_IMAGE=$(echo $SINGULARITY_IMAGE | sed "s:#SINGULARITY_IMAGE_TAG:${SINGULARITY_IMAGE_TAG}:g")
 
-        function xfconf-query(){ singularity exec instance://${SINGULARITY_INSTANCE} xfconf-query $@; }
-        export -f xfconf-query
-        function xfce4-session(){ singularity exec instance://${SINGULARITY_INSTANCE} xfce4-session $@; }
-        export -f xfce4-session
+          # start the container instance
+          if [ ! -f "${SINGULARITY_IMAGE}" ]; then
+            echo "Error! could not find singularity image ${SINGULARITY_IMAGE}." 
+            exit 127
+          fi
 
-        function gsettings(){ singularity exec instance://${SINGULARITY_INSTANCE} gsettings $@; }
-        export -f gsettings
-        function dconf(){ singularity exec instance://${SINGULARITY_INSTANCE} dconf $@; }
-        export -f dconf
-        function mate-session(){ singularity exec instance://${SINGULARITY_INSTANCE} mate-session $@; }
-        export -f mate-session
+          # start container
+          export SINGULARITY_INSTANCE=$(basename -- $XDG_RUNTIME_DIR) 
+          echo "Starting image ${SINGULARITY_IMAGE} as ${SINGULARITY_INSTANCE}..."
+          echo singularity instance start -B /sdf,/gpfs,/scratch,/lscratch,${XDG_RUNTIME_DIR}:/tmp --nv ${SINGULARITY_OPTIONS} ${SINGULARITY_IMAGE} ${SINGULARITY_INSTANCE}
+          singularity instance start -B /sdf,/gpfs,/scratch,/lscratch,${XDG_RUNTIME_DIR}:/tmp --nv ${SINGULARITY_OPTIONS} ${SINGULARITY_IMAGE} ${SINGULARITY_INSTANCE}
 
-        function websockify(){ singularity exec instance://${SINGULARITY_INSTANCE} websockify $@; }
-        export -f websockify
+          # alias doesn't work for some reason...
+          function kill(){ singularity exec instance://${SINGULARITY_INSTANCE} kill $@; }
+          export -f kill
+          function pkill(){ singularity exec instance://${SINGULARITY_INSTANCE} pkill $@; }
+          export -f pkill
+          function pgrep(){ singularity exec instance://${SINGULARITY_INSTANCE} pgrep $@; }
+          export -f pgrep
+          function vncserver(){ singularity exec instance://${SINGULARITY_INSTANCE} vncserver $@; }
+          export -f vncserver
+          function vncpasswd(){ singularity exec instance://${SINGULARITY_INSTANCE} vncpasswd $@; }
+          export -f vncpasswd
+
+          function xfconf-query(){ singularity exec instance://${SINGULARITY_INSTANCE} xfconf-query $@; }
+          export -f xfconf-query
+          function xfce4-session(){ singularity exec instance://${SINGULARITY_INSTANCE} xfce4-session $@; }
+          export -f xfce4-session
+
+          function gsettings(){ singularity exec instance://${SINGULARITY_INSTANCE} gsettings $@; }
+          export -f gsettings
+          function dconf(){ singularity exec instance://${SINGULARITY_INSTANCE} dconf $@; }
+          export -f dconf
+          function mate-session(){ singularity exec instance://${SINGULARITY_INSTANCE} mate-session $@; }
+          export -f mate-session
+
+          function websockify(){ singularity exec instance://${SINGULARITY_INSTANCE} websockify $@; }
+          export -f websockify
+
+        fi # singularity image
 
         %s
       set_host: "host=$(hostname -s)"
