changes to singularity desktop boot

diff --git a/kubernetes/overlays/dev/etc/sdf_cluster.yml b/kubernetes/overlays/dev/etc/sdf_cluster.yml
--- a/kubernetes/overlays/dev/etc/sdf_cluster.yml
+++ b/kubernetes/overlays/dev/etc/sdf_cluster.yml
@@ -35,8 +35,8 @@ v2:
         # deal with booting up a singularity image
         if [ ! -z "$SINGULARITY_IMAGE" ]; then
 
-          printenv SINGULARITY_IMAGE_TAG
-          echo $(echo $SINGULARITY_IMAGE | sed "s:#SINGULARITY_IMAGE_TAG:${SINGULARITY_IMAGE_TAG}:g")
+          #printenv SINGULARITY_IMAGE_TAG
+          #echo $(echo $SINGULARITY_IMAGE | sed "s:#SINGULARITY_IMAGE_TAG:${SINGULARITY_IMAGE_TAG}:g")
           # parse any variables help in image name
           eval export SINGULARITY_IMAGE=$(echo $SINGULARITY_IMAGE | sed "s:#SINGULARITY_IMAGE_TAG:${SINGULARITY_IMAGE_TAG}:g")
 
@@ -49,8 +49,14 @@ v2:
           # start container
           export SINGULARITY_INSTANCE=$(basename -- $XDG_RUNTIME_DIR)
           echo "Starting image ${SINGULARITY_IMAGE} as ${SINGULARITY_INSTANCE}..."
-          echo singularity instance start -B /sdf,/gpfs,/scratch,/lscratch,${XDG_RUNTIME_DIR}:/tmp --nv ${SINGULARITY_OPTIONS} ${SINGULARITY_IMAGE} ${SINGULARITY_INSTANCE}
-          singularity instance start -B /sdf,/gpfs,/scratch,/lscratch,${XDG_RUNTIME_DIR}:/tmp --nv ${SINGULARITY_OPTIONS} ${SINGULARITY_IMAGE} ${SINGULARITY_INSTANCE}
+          OPTIONS=$(cat user_defined_context.json | awk '/SINGULARITY_OPTIONS/{ gsub(/^\s+\"SINGULARITY_OPTIONS\": \"/,"",$0); gsub(/\"\,\s*$/,"",$0); gsub(/\\r/,"",$0); print $0 }')
+          echo singularity instance start -B /sdf,/gpfs,/scratch,/lscratch,${XDG_RUNTIME_DIR}:/tmp --nv $(eval echo -e ${OPTIONS})  ${SINGULARITY_IMAGE} ${SINGULARITY_INSTANCE}
+          singularity instance start -B /sdf,/gpfs,/scratch,/lscratch,${XDG_RUNTIME_DIR}:/tmp --nv $(eval echo -e ${OPTIONS})  ${SINGULARITY_IMAGE} ${SINGULARITY_INSTANCE}
+          EXIT=$?
+          if [ "${EXIT}" != "0" ]; then
+            echo "Error! could not initiate singularity container."
+            exit ${EXIT}
+          fi 
 
           # alias doesn't work for some reason...
           function kill(){ singularity exec instance://${SINGULARITY_INSTANCE} kill $@; }
